name: social_media_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0
  equatable: ^2.0.3
  image_picker: ^0.8.4+2
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.1
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/ui/assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ui/assets/icons/launcher_icon.png"

flutter_app_name:
  name: "Social Media"
